[api]
meta_api=https://apollo.baidu.com/packages/api/depo
download=https://apollo.baidu.com/packages/api/package/download
login=https://apollo.baidu.com/packages/api/login
attr_query=https://apollo.baidu.com/packages/api/package/attr

[cache]
offline_metadata_prefix=/opt/apollo/neo/share/buildtool/namespaces
offline_packages_filename=Packages
ld_cache=ld.cache
offline_cyberfile_cache_filename=Cyberfiles

[decider]
targets=/opt/apollo/neo/share/buildtool/targets
results=/opt/apollo/neo/share/buildtool/results
cyberfile_source=/opt/apollo/neo/share/buildtool/cyberfile_source

[base]
external_path=/usr/include
apollo_root=/opt/apollo/neo
apollo_package_path=/opt/apollo/neo/packages
deprecated_package_path=packages
apollo_lib_path=/opt/apollo/neo/lib
apollo_include_path=/opt/apollo/neo/include

source_path_prefix=src
binary_path_prefix=bin
include_path_prefix=include
python_path_prefix=python
library_path_prefix=lib
package_meta_prefix=share/packages
config_path_prefix=share
playgroud_prefix=playgroud

[compile]
march=-march=native
